# coding: utf-8

"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dedi_client.models.verify_email200_response_data import VerifyEmail200ResponseData

class TestVerifyEmail200ResponseData(unittest.TestCase):
    """VerifyEmail200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyEmail200ResponseData:
        """Test VerifyEmail200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyEmail200ResponseData`
        """
        model = VerifyEmail200ResponseData()
        if include_optional:
            return VerifyEmail200ResponseData(
                refresh_token = ''
            )
        else:
            return VerifyEmail200ResponseData(
        )
        """

    def testVerifyEmail200ResponseData(self):
        """Test VerifyEmail200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
