# coding: utf-8

# flake8: noqa
"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from dedi_client.models.add_registry_delegate_request import AddRegistryDelegateRequest
from dedi_client.models.archive_registry200_response import ArchiveRegistry200Response
from dedi_client.models.bulk_upload_records202_response import BulkUploadRecords202Response
from dedi_client.models.bulk_upload_records202_response_data import BulkUploadRecords202ResponseData
from dedi_client.models.change_record_state200_response import ChangeRecordState200Response
from dedi_client.models.change_record_state_request import ChangeRecordStateRequest
from dedi_client.models.check_domain_verification200_response import CheckDomainVerification200Response
from dedi_client.models.check_domain_verification200_response_data import CheckDomainVerification200ResponseData
from dedi_client.models.confirm_password_reset_request import ConfirmPasswordResetRequest
from dedi_client.models.create_namespace201_response import CreateNamespace201Response
from dedi_client.models.create_namespace_request import CreateNamespaceRequest
from dedi_client.models.create_registry201_response import CreateRegistry201Response
from dedi_client.models.create_registry_request import CreateRegistryRequest
from dedi_client.models.error_response import ErrorResponse
from dedi_client.models.forgot_password_request import ForgotPasswordRequest
from dedi_client.models.generate_txt_record200_response import GenerateTxtRecord200Response
from dedi_client.models.generate_txt_record200_response_data import GenerateTxtRecord200ResponseData
from dedi_client.models.get_api_key200_response import GetApiKey200Response
from dedi_client.models.get_api_key200_response_data import GetApiKey200ResponseData
from dedi_client.models.get_current_user200_response import GetCurrentUser200Response
from dedi_client.models.get_job_status200_response import GetJobStatus200Response
from dedi_client.models.get_namespace_versions200_response import GetNamespaceVersions200Response
from dedi_client.models.get_namespace_versions200_response_data import GetNamespaceVersions200ResponseData
from dedi_client.models.get_platform_statistics200_response import GetPlatformStatistics200Response
from dedi_client.models.get_record_versions200_response import GetRecordVersions200Response
from dedi_client.models.get_record_versions200_response_data import GetRecordVersions200ResponseData
from dedi_client.models.get_registry_versions200_response import GetRegistryVersions200Response
from dedi_client.models.get_registry_versions200_response_data import GetRegistryVersions200ResponseData
from dedi_client.models.get_user_jobs200_response import GetUserJobs200Response
from dedi_client.models.get_user_watch_subscriptions200_response import GetUserWatchSubscriptions200Response
from dedi_client.models.get_user_watch_subscriptions200_response_data_inner import GetUserWatchSubscriptions200ResponseDataInner
from dedi_client.models.job_status import JobStatus
from dedi_client.models.job_status_progress import JobStatusProgress
from dedi_client.models.lookup_namespace200_response import LookupNamespace200Response
from dedi_client.models.lookup_record200_response import LookupRecord200Response
from dedi_client.models.lookup_registry200_response import LookupRegistry200Response
from dedi_client.models.namespace import Namespace
from dedi_client.models.publish_record201_response import PublishRecord201Response
from dedi_client.models.publish_record_request import PublishRecordRequest
from dedi_client.models.query_namespace_registries200_response import QueryNamespaceRegistries200Response
from dedi_client.models.query_namespace_registries200_response_data import QueryNamespaceRegistries200ResponseData
from dedi_client.models.query_registry_records200_response import QueryRegistryRecords200Response
from dedi_client.models.query_registry_records200_response_data import QueryRegistryRecords200ResponseData
from dedi_client.models.record import Record
from dedi_client.models.record_summary import RecordSummary
from dedi_client.models.refresh_token200_response import RefreshToken200Response
from dedi_client.models.refresh_token_request import RefreshTokenRequest
from dedi_client.models.register_login_request import RegisterLoginRequest
from dedi_client.models.registry import Registry
from dedi_client.models.registry_summary import RegistrySummary
from dedi_client.models.reinstate_record200_response import ReinstateRecord200Response
from dedi_client.models.reinstate_registry200_response import ReinstateRegistry200Response
from dedi_client.models.remove_namespace_verification200_response import RemoveNamespaceVerification200Response
from dedi_client.models.remove_namespace_verification404_response import RemoveNamespaceVerification404Response
from dedi_client.models.remove_namespace_verification500_response import RemoveNamespaceVerification500Response
from dedi_client.models.remove_registry_delegate_request import RemoveRegistryDelegateRequest
from dedi_client.models.resend_magic_link_request import ResendMagicLinkRequest
from dedi_client.models.reset_password_request import ResetPasswordRequest
from dedi_client.models.restore_registry200_response import RestoreRegistry200Response
from dedi_client.models.revoke_record200_response import RevokeRecord200Response
from dedi_client.models.revoke_registry200_response import RevokeRegistry200Response
from dedi_client.models.save_record_as_draft201_response import SaveRecordAsDraft201Response
from dedi_client.models.save_record_as_draft_request import SaveRecordAsDraftRequest
from dedi_client.models.search_records200_response import SearchRecords200Response
from dedi_client.models.search_records200_response_data_inner import SearchRecords200ResponseDataInner
from dedi_client.models.subscribe_to_watch201_response import SubscribeToWatch201Response
from dedi_client.models.subscribe_to_watch201_response_data import SubscribeToWatch201ResponseData
from dedi_client.models.subscribe_to_watch_request import SubscribeToWatchRequest
from dedi_client.models.success_response import SuccessResponse
from dedi_client.models.suspend_record200_response import SuspendRecord200Response
from dedi_client.models.update_namespace_request import UpdateNamespaceRequest
from dedi_client.models.update_record_request import UpdateRecordRequest
from dedi_client.models.update_registry_request import UpdateRegistryRequest
from dedi_client.models.user import User
from dedi_client.models.verify_domain_request import VerifyDomainRequest
from dedi_client.models.verify_email200_response import VerifyEmail200Response
from dedi_client.models.verify_email200_response_data import VerifyEmail200ResponseData
from dedi_client.models.verify_namespace_lookup_request import VerifyNamespaceLookupRequest
from dedi_client.models.verify_record_lookup_request import VerifyRecordLookupRequest
from dedi_client.models.verify_registry_lookup_request import VerifyRegistryLookupRequest
from dedi_client.models.watch_subscription import WatchSubscription

