"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from dedi_client.models.query_namespace_registries200_response import QueryNamespaceRegistries200Response
from dedi_client.models.query_registry_records200_response import QueryRegistryRecords200Response

from dedi_client.api_client import ApiClient, RequestSerialized
from dedi_client.api_response import ApiResponse
from dedi_client.rest import RESTResponseType


class QueryApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def query_namespace_registries(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        var_from: Annotated[Optional[date], Field(description="Filter registries updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter registries updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by registry state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by registry name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueryNamespaceRegistries200Response:
        """Query namespace registries

        Queries all registries within a namespace with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param var_from: Filter registries updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter registries updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by registry state
        :type state: str
        :param name: Search by registry name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_namespace_registries_serialize(
            namespace=namespace,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryNamespaceRegistries200Response",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def query_namespace_registries_with_http_info(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        var_from: Annotated[Optional[date], Field(description="Filter registries updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter registries updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by registry state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by registry name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueryNamespaceRegistries200Response]:
        """Query namespace registries

        Queries all registries within a namespace with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param var_from: Filter registries updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter registries updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by registry state
        :type state: str
        :param name: Search by registry name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_namespace_registries_serialize(
            namespace=namespace,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryNamespaceRegistries200Response",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def query_namespace_registries_without_preload_content(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        var_from: Annotated[Optional[date], Field(description="Filter registries updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter registries updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by registry state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by registry name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Query namespace registries

        Queries all registries within a namespace with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param var_from: Filter registries updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter registries updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by registry state
        :type state: str
        :param name: Search by registry name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_namespace_registries_serialize(
            namespace=namespace,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryNamespaceRegistries200Response",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _query_namespace_registries_serialize(
        self,
        namespace,
        var_from,
        to,
        state,
        name,
        sort,
        page,
        page_size,
        as_on,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if namespace is not None:
            _path_params['namespace'] = namespace
        # process the query parameters
        if var_from is not None:
            if isinstance(var_from, date):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, date):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if state is not None:
            
            _query_params.append(('state', state))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if as_on is not None:
            if isinstance(as_on, date):
                _query_params.append(
                    (
                        'as_on',
                        as_on.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('as_on', as_on))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'CookieAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dedi/query/{namespace}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def query_registry_records(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        registry_name: Annotated[StrictStr, Field(description="Registry name to query")],
        var_from: Annotated[Optional[date], Field(description="Filter records updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter records updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by record state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by record name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> QueryRegistryRecords200Response:
        """Query registry records

        Queries all records within a registry with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param registry_name: Registry name to query (required)
        :type registry_name: str
        :param var_from: Filter records updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter records updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by record state
        :type state: str
        :param name: Search by record name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_registry_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryRegistryRecords200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def query_registry_records_with_http_info(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        registry_name: Annotated[StrictStr, Field(description="Registry name to query")],
        var_from: Annotated[Optional[date], Field(description="Filter records updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter records updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by record state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by record name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[QueryRegistryRecords200Response]:
        """Query registry records

        Queries all records within a registry with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param registry_name: Registry name to query (required)
        :type registry_name: str
        :param var_from: Filter records updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter records updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by record state
        :type state: str
        :param name: Search by record name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_registry_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryRegistryRecords200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def query_registry_records_without_preload_content(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name")],
        registry_name: Annotated[StrictStr, Field(description="Registry name to query")],
        var_from: Annotated[Optional[date], Field(description="Filter records updated from date (YYYY-MM-DD)")] = None,
        to: Annotated[Optional[date], Field(description="Filter records updated to date (YYYY-MM-DD)")] = None,
        state: Annotated[Optional[StrictStr], Field(description="Filter by record state")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Search by record name (minimum 3 characters)")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Sort results")] = None,
        page: Annotated[Optional[Annotated[int, Field(strict=True, ge=1)]], Field(description="Page number for pagination")] = None,
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Items per page")] = None,
        as_on: Annotated[Optional[date], Field(description="Historical query date (YYYY-MM-DD)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Query registry records

        Queries all records within a registry with filtering and pagination support. 

        :param namespace: Namespace ID or domain name (required)
        :type namespace: str
        :param registry_name: Registry name to query (required)
        :type registry_name: str
        :param var_from: Filter records updated from date (YYYY-MM-DD)
        :type var_from: date
        :param to: Filter records updated to date (YYYY-MM-DD)
        :type to: date
        :param state: Filter by record state
        :type state: str
        :param name: Search by record name (minimum 3 characters)
        :type name: str
        :param sort: Sort results
        :type sort: str
        :param page: Page number for pagination
        :type page: int
        :param page_size: Items per page
        :type page_size: int
        :param as_on: Historical query date (YYYY-MM-DD)
        :type as_on: date
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._query_registry_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            var_from=var_from,
            to=to,
            state=state,
            name=name,
            sort=sort,
            page=page,
            page_size=page_size,
            as_on=as_on,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "QueryRegistryRecords200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _query_registry_records_serialize(
        self,
        namespace,
        registry_name,
        var_from,
        to,
        state,
        name,
        sort,
        page,
        page_size,
        as_on,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if namespace is not None:
            _path_params['namespace'] = namespace
        if registry_name is not None:
            _path_params['registry_name'] = registry_name
        # process the query parameters
        if var_from is not None:
            if isinstance(var_from, date):
                _query_params.append(
                    (
                        'from',
                        var_from.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('from', var_from))
            
        if to is not None:
            if isinstance(to, date):
                _query_params.append(
                    (
                        'to',
                        to.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('to', to))
            
        if state is not None:
            
            _query_params.append(('state', state))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if page_size is not None:
            
            _query_params.append(('page_size', page_size))
            
        if as_on is not None:
            if isinstance(as_on, date):
                _query_params.append(
                    (
                        'as_on',
                        as_on.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('as_on', as_on))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'CookieAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dedi/query/{namespace}/{registry_name}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


