"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from dedi_client.models.search_records200_response import SearchRecords200Response

from dedi_client.api_client import ApiClient, RequestSerialized
from dedi_client.api_response import ApiResponse
from dedi_client.rest import RESTResponseType


class SearchApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def search_records(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name to search within")],
        registry_name: Annotated[Optional[StrictStr], Field(description="Filter by registry name (partial match)")] = None,
        record_name: Annotated[Optional[StrictStr], Field(description="Search by record name (partial match)")] = None,
        email: Annotated[Optional[StrictStr], Field(description="Search by email field in record details")] = None,
        public_key: Annotated[Optional[StrictStr], Field(description="Search by publicKey field in record details")] = None,
        detail_address: Annotated[Optional[StrictStr], Field(description="Example - Search nested field using dot notation")] = None,
        profile_name: Annotated[Optional[StrictStr], Field(description="Example - Search deeply nested field")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SearchRecords200Response:
        """Advanced record search

        Powerful search functionality across all records in a namespace with support for nested field searching and flexible filtering.  **Search Capabilities:** - Registry filtering by name - Record name search with partial matching - Direct field search in record details - Nested field search using dot notation - Multiple criteria combination - Case-insensitive partial matching  **Field Search Examples:** - Basic fields: `email`, `publicKey`, `phone`, `name` - Nested fields: `detail.address`, `profile.name`, `contact.email` - Deep nesting: `data.user.profile.settings.theme` 

        :param namespace: Namespace ID or domain name to search within (required)
        :type namespace: str
        :param registry_name: Filter by registry name (partial match)
        :type registry_name: str
        :param record_name: Search by record name (partial match)
        :type record_name: str
        :param email: Search by email field in record details
        :type email: str
        :param public_key: Search by publicKey field in record details
        :type public_key: str
        :param detail_address: Example - Search nested field using dot notation
        :type detail_address: str
        :param profile_name: Example - Search deeply nested field
        :type profile_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            record_name=record_name,
            email=email,
            public_key=public_key,
            detail_address=detail_address,
            profile_name=profile_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchRecords200Response",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_records_with_http_info(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name to search within")],
        registry_name: Annotated[Optional[StrictStr], Field(description="Filter by registry name (partial match)")] = None,
        record_name: Annotated[Optional[StrictStr], Field(description="Search by record name (partial match)")] = None,
        email: Annotated[Optional[StrictStr], Field(description="Search by email field in record details")] = None,
        public_key: Annotated[Optional[StrictStr], Field(description="Search by publicKey field in record details")] = None,
        detail_address: Annotated[Optional[StrictStr], Field(description="Example - Search nested field using dot notation")] = None,
        profile_name: Annotated[Optional[StrictStr], Field(description="Example - Search deeply nested field")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SearchRecords200Response]:
        """Advanced record search

        Powerful search functionality across all records in a namespace with support for nested field searching and flexible filtering.  **Search Capabilities:** - Registry filtering by name - Record name search with partial matching - Direct field search in record details - Nested field search using dot notation - Multiple criteria combination - Case-insensitive partial matching  **Field Search Examples:** - Basic fields: `email`, `publicKey`, `phone`, `name` - Nested fields: `detail.address`, `profile.name`, `contact.email` - Deep nesting: `data.user.profile.settings.theme` 

        :param namespace: Namespace ID or domain name to search within (required)
        :type namespace: str
        :param registry_name: Filter by registry name (partial match)
        :type registry_name: str
        :param record_name: Search by record name (partial match)
        :type record_name: str
        :param email: Search by email field in record details
        :type email: str
        :param public_key: Search by publicKey field in record details
        :type public_key: str
        :param detail_address: Example - Search nested field using dot notation
        :type detail_address: str
        :param profile_name: Example - Search deeply nested field
        :type profile_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            record_name=record_name,
            email=email,
            public_key=public_key,
            detail_address=detail_address,
            profile_name=profile_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchRecords200Response",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_records_without_preload_content(
        self,
        namespace: Annotated[StrictStr, Field(description="Namespace ID or domain name to search within")],
        registry_name: Annotated[Optional[StrictStr], Field(description="Filter by registry name (partial match)")] = None,
        record_name: Annotated[Optional[StrictStr], Field(description="Search by record name (partial match)")] = None,
        email: Annotated[Optional[StrictStr], Field(description="Search by email field in record details")] = None,
        public_key: Annotated[Optional[StrictStr], Field(description="Search by publicKey field in record details")] = None,
        detail_address: Annotated[Optional[StrictStr], Field(description="Example - Search nested field using dot notation")] = None,
        profile_name: Annotated[Optional[StrictStr], Field(description="Example - Search deeply nested field")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Advanced record search

        Powerful search functionality across all records in a namespace with support for nested field searching and flexible filtering.  **Search Capabilities:** - Registry filtering by name - Record name search with partial matching - Direct field search in record details - Nested field search using dot notation - Multiple criteria combination - Case-insensitive partial matching  **Field Search Examples:** - Basic fields: `email`, `publicKey`, `phone`, `name` - Nested fields: `detail.address`, `profile.name`, `contact.email` - Deep nesting: `data.user.profile.settings.theme` 

        :param namespace: Namespace ID or domain name to search within (required)
        :type namespace: str
        :param registry_name: Filter by registry name (partial match)
        :type registry_name: str
        :param record_name: Search by record name (partial match)
        :type record_name: str
        :param email: Search by email field in record details
        :type email: str
        :param public_key: Search by publicKey field in record details
        :type public_key: str
        :param detail_address: Example - Search nested field using dot notation
        :type detail_address: str
        :param profile_name: Example - Search deeply nested field
        :type profile_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_records_serialize(
            namespace=namespace,
            registry_name=registry_name,
            record_name=record_name,
            email=email,
            public_key=public_key,
            detail_address=detail_address,
            profile_name=profile_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchRecords200Response",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_records_serialize(
        self,
        namespace,
        registry_name,
        record_name,
        email,
        public_key,
        detail_address,
        profile_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if namespace is not None:
            _path_params['namespace'] = namespace
        # process the query parameters
        if registry_name is not None:
            
            _query_params.append(('registry_name', registry_name))
            
        if record_name is not None:
            
            _query_params.append(('record_name', record_name))
            
        if email is not None:
            
            _query_params.append(('email', email))
            
        if public_key is not None:
            
            _query_params.append(('publicKey', public_key))
            
        if detail_address is not None:
            
            _query_params.append(('detail.address', detail_address))
            
        if profile_name is not None:
            
            _query_params.append(('profile.name', profile_name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'CookieAuth', 
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/dedi/search/{namespace}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


