"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "dedi-api-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="DeDi API",
    author="DeDi Support",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "DeDi API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 
    """,  # noqa: E501
    package_data={"dedi_client": ["py.typed"]},
)
