# coding: utf-8

# flake8: noqa

"""
    DeDi API

    DeDi (Decentralized Directory) API provides comprehensive functionality for managing  namespaces, registries, and records in a decentralized directory system.  ## Authentication  The API supports dual authentication methods: - **API Key Authentication**: Bearer token in Authorization header (recommended for production) - **Cookie Authentication**: Token cookie for browser integration  All authentication endpoints now support password-based authentication with robust security requirements.  ## Base Concepts  - **Namespace**: Top-level organization unit for grouping related registries - **Registry**: Schema-defined container for records within a namespace   - **Record**: Individual data entries conforming to registry schema  ## Key Features  - **Password-based Authentication**: Secure login with enforced password complexity - **Domain Verification**: Verify ownership of domains for namespace binding - **Bulk Operations**: CSV import/export for large-scale data management - **Real-time Notifications**: Watch system for monitoring changes via webhooks - **Delegation Management**: Fine-grained access control and user permissions - **Version Control**: Complete history tracking for all resources - **Advanced Search**: Powerful search with nested field support - **State Management**: Comprehensive lifecycle management for registries and records  ## Rate Limiting  Standard rate limits apply to all endpoints. Contact support for enterprise limits.  ## Production Readiness  This API specification is production-grade and includes: - Comprehensive error handling with detailed error codes - Extensive documentation with examples - Security best practices implementation - Scalable architecture design - Full CRUD operations for all resources 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccessApi",
    "AuthenticationApi",
    "DelegationApi",
    "DomainVerificationApi",
    "PublishingApi",
    "QueryApi",
    "SearchApi",
    "StateManagementApi",
    "StatisticsApi",
    "UpdatesApi",
    "VerificationLookupApi",
    "VersionsApi",
    "WatchNotificationsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddRegistryDelegateRequest",
    "ArchiveRegistry200Response",
    "BulkUploadRecords202Response",
    "BulkUploadRecords202ResponseData",
    "ChangeRecordState200Response",
    "ChangeRecordStateRequest",
    "CheckDomainVerification200Response",
    "CheckDomainVerification200ResponseData",
    "ConfirmPasswordResetRequest",
    "CreateNamespace201Response",
    "CreateNamespaceRequest",
    "CreateRegistry201Response",
    "CreateRegistryRequest",
    "ErrorResponse",
    "ForgotPasswordRequest",
    "GenerateTxtRecord200Response",
    "GenerateTxtRecord200ResponseData",
    "GetApiKey200Response",
    "GetApiKey200ResponseData",
    "GetCurrentUser200Response",
    "GetJobStatus200Response",
    "GetNamespaceVersions200Response",
    "GetNamespaceVersions200ResponseData",
    "GetPlatformStatistics200Response",
    "GetRecordVersions200Response",
    "GetRecordVersions200ResponseData",
    "GetRegistryVersions200Response",
    "GetRegistryVersions200ResponseData",
    "GetUserJobs200Response",
    "GetUserWatchSubscriptions200Response",
    "GetUserWatchSubscriptions200ResponseDataInner",
    "JobStatus",
    "JobStatusProgress",
    "LookupNamespace200Response",
    "LookupRecord200Response",
    "LookupRegistry200Response",
    "Namespace",
    "PublishRecord201Response",
    "PublishRecordRequest",
    "QueryNamespaceRegistries200Response",
    "QueryNamespaceRegistries200ResponseData",
    "QueryRegistryRecords200Response",
    "QueryRegistryRecords200ResponseData",
    "Record",
    "RecordSummary",
    "RefreshToken200Response",
    "RefreshTokenRequest",
    "RegisterLoginRequest",
    "Registry",
    "RegistrySummary",
    "ReinstateRecord200Response",
    "ReinstateRegistry200Response",
    "RemoveNamespaceVerification200Response",
    "RemoveNamespaceVerification404Response",
    "RemoveNamespaceVerification500Response",
    "RemoveRegistryDelegateRequest",
    "ResendMagicLinkRequest",
    "ResetPasswordRequest",
    "RestoreRegistry200Response",
    "RevokeRecord200Response",
    "RevokeRegistry200Response",
    "SaveRecordAsDraft201Response",
    "SaveRecordAsDraftRequest",
    "SearchRecords200Response",
    "SearchRecords200ResponseDataInner",
    "SubscribeToWatch201Response",
    "SubscribeToWatch201ResponseData",
    "SubscribeToWatchRequest",
    "SuccessResponse",
    "SuspendRecord200Response",
    "UpdateNamespaceRequest",
    "UpdateRecordRequest",
    "UpdateRegistryRequest",
    "User",
    "VerifyDomainRequest",
    "VerifyEmail200Response",
    "VerifyEmail200ResponseData",
    "VerifyNamespaceLookupRequest",
    "VerifyRecordLookupRequest",
    "VerifyRegistryLookupRequest",
    "WatchSubscription",
]

# import apis into sdk package
from dedi_client.api.access_api import AccessApi as AccessApi
from dedi_client.api.authentication_api import AuthenticationApi as AuthenticationApi
from dedi_client.api.delegation_api import DelegationApi as DelegationApi
from dedi_client.api.domain_verification_api import DomainVerificationApi as DomainVerificationApi
from dedi_client.api.publishing_api import PublishingApi as PublishingApi
from dedi_client.api.query_api import QueryApi as QueryApi
from dedi_client.api.search_api import SearchApi as SearchApi
from dedi_client.api.state_management_api import StateManagementApi as StateManagementApi
from dedi_client.api.statistics_api import StatisticsApi as StatisticsApi
from dedi_client.api.updates_api import UpdatesApi as UpdatesApi
from dedi_client.api.verification_lookup_api import VerificationLookupApi as VerificationLookupApi
from dedi_client.api.versions_api import VersionsApi as VersionsApi
from dedi_client.api.watch_notifications_api import WatchNotificationsApi as WatchNotificationsApi

# import ApiClient
from dedi_client.api_response import ApiResponse as ApiResponse
from dedi_client.api_client import ApiClient as ApiClient
from dedi_client.configuration import Configuration as Configuration
from dedi_client.exceptions import OpenApiException as OpenApiException
from dedi_client.exceptions import ApiTypeError as ApiTypeError
from dedi_client.exceptions import ApiValueError as ApiValueError
from dedi_client.exceptions import ApiKeyError as ApiKeyError
from dedi_client.exceptions import ApiAttributeError as ApiAttributeError
from dedi_client.exceptions import ApiException as ApiException

# import models into sdk package
from dedi_client.models.add_registry_delegate_request import AddRegistryDelegateRequest as AddRegistryDelegateRequest
from dedi_client.models.archive_registry200_response import ArchiveRegistry200Response as ArchiveRegistry200Response
from dedi_client.models.bulk_upload_records202_response import BulkUploadRecords202Response as BulkUploadRecords202Response
from dedi_client.models.bulk_upload_records202_response_data import BulkUploadRecords202ResponseData as BulkUploadRecords202ResponseData
from dedi_client.models.change_record_state200_response import ChangeRecordState200Response as ChangeRecordState200Response
from dedi_client.models.change_record_state_request import ChangeRecordStateRequest as ChangeRecordStateRequest
from dedi_client.models.check_domain_verification200_response import CheckDomainVerification200Response as CheckDomainVerification200Response
from dedi_client.models.check_domain_verification200_response_data import CheckDomainVerification200ResponseData as CheckDomainVerification200ResponseData
from dedi_client.models.confirm_password_reset_request import ConfirmPasswordResetRequest as ConfirmPasswordResetRequest
from dedi_client.models.create_namespace201_response import CreateNamespace201Response as CreateNamespace201Response
from dedi_client.models.create_namespace_request import CreateNamespaceRequest as CreateNamespaceRequest
from dedi_client.models.create_registry201_response import CreateRegistry201Response as CreateRegistry201Response
from dedi_client.models.create_registry_request import CreateRegistryRequest as CreateRegistryRequest
from dedi_client.models.error_response import ErrorResponse as ErrorResponse
from dedi_client.models.forgot_password_request import ForgotPasswordRequest as ForgotPasswordRequest
from dedi_client.models.generate_txt_record200_response import GenerateTxtRecord200Response as GenerateTxtRecord200Response
from dedi_client.models.generate_txt_record200_response_data import GenerateTxtRecord200ResponseData as GenerateTxtRecord200ResponseData
from dedi_client.models.get_api_key200_response import GetApiKey200Response as GetApiKey200Response
from dedi_client.models.get_api_key200_response_data import GetApiKey200ResponseData as GetApiKey200ResponseData
from dedi_client.models.get_current_user200_response import GetCurrentUser200Response as GetCurrentUser200Response
from dedi_client.models.get_job_status200_response import GetJobStatus200Response as GetJobStatus200Response
from dedi_client.models.get_namespace_versions200_response import GetNamespaceVersions200Response as GetNamespaceVersions200Response
from dedi_client.models.get_namespace_versions200_response_data import GetNamespaceVersions200ResponseData as GetNamespaceVersions200ResponseData
from dedi_client.models.get_platform_statistics200_response import GetPlatformStatistics200Response as GetPlatformStatistics200Response
from dedi_client.models.get_record_versions200_response import GetRecordVersions200Response as GetRecordVersions200Response
from dedi_client.models.get_record_versions200_response_data import GetRecordVersions200ResponseData as GetRecordVersions200ResponseData
from dedi_client.models.get_registry_versions200_response import GetRegistryVersions200Response as GetRegistryVersions200Response
from dedi_client.models.get_registry_versions200_response_data import GetRegistryVersions200ResponseData as GetRegistryVersions200ResponseData
from dedi_client.models.get_user_jobs200_response import GetUserJobs200Response as GetUserJobs200Response
from dedi_client.models.get_user_watch_subscriptions200_response import GetUserWatchSubscriptions200Response as GetUserWatchSubscriptions200Response
from dedi_client.models.get_user_watch_subscriptions200_response_data_inner import GetUserWatchSubscriptions200ResponseDataInner as GetUserWatchSubscriptions200ResponseDataInner
from dedi_client.models.job_status import JobStatus as JobStatus
from dedi_client.models.job_status_progress import JobStatusProgress as JobStatusProgress
from dedi_client.models.lookup_namespace200_response import LookupNamespace200Response as LookupNamespace200Response
from dedi_client.models.lookup_record200_response import LookupRecord200Response as LookupRecord200Response
from dedi_client.models.lookup_registry200_response import LookupRegistry200Response as LookupRegistry200Response
from dedi_client.models.namespace import Namespace as Namespace
from dedi_client.models.publish_record201_response import PublishRecord201Response as PublishRecord201Response
from dedi_client.models.publish_record_request import PublishRecordRequest as PublishRecordRequest
from dedi_client.models.query_namespace_registries200_response import QueryNamespaceRegistries200Response as QueryNamespaceRegistries200Response
from dedi_client.models.query_namespace_registries200_response_data import QueryNamespaceRegistries200ResponseData as QueryNamespaceRegistries200ResponseData
from dedi_client.models.query_registry_records200_response import QueryRegistryRecords200Response as QueryRegistryRecords200Response
from dedi_client.models.query_registry_records200_response_data import QueryRegistryRecords200ResponseData as QueryRegistryRecords200ResponseData
from dedi_client.models.record import Record as Record
from dedi_client.models.record_summary import RecordSummary as RecordSummary
from dedi_client.models.refresh_token200_response import RefreshToken200Response as RefreshToken200Response
from dedi_client.models.refresh_token_request import RefreshTokenRequest as RefreshTokenRequest
from dedi_client.models.register_login_request import RegisterLoginRequest as RegisterLoginRequest
from dedi_client.models.registry import Registry as Registry
from dedi_client.models.registry_summary import RegistrySummary as RegistrySummary
from dedi_client.models.reinstate_record200_response import ReinstateRecord200Response as ReinstateRecord200Response
from dedi_client.models.reinstate_registry200_response import ReinstateRegistry200Response as ReinstateRegistry200Response
from dedi_client.models.remove_namespace_verification200_response import RemoveNamespaceVerification200Response as RemoveNamespaceVerification200Response
from dedi_client.models.remove_namespace_verification404_response import RemoveNamespaceVerification404Response as RemoveNamespaceVerification404Response
from dedi_client.models.remove_namespace_verification500_response import RemoveNamespaceVerification500Response as RemoveNamespaceVerification500Response
from dedi_client.models.remove_registry_delegate_request import RemoveRegistryDelegateRequest as RemoveRegistryDelegateRequest
from dedi_client.models.resend_magic_link_request import ResendMagicLinkRequest as ResendMagicLinkRequest
from dedi_client.models.reset_password_request import ResetPasswordRequest as ResetPasswordRequest
from dedi_client.models.restore_registry200_response import RestoreRegistry200Response as RestoreRegistry200Response
from dedi_client.models.revoke_record200_response import RevokeRecord200Response as RevokeRecord200Response
from dedi_client.models.revoke_registry200_response import RevokeRegistry200Response as RevokeRegistry200Response
from dedi_client.models.save_record_as_draft201_response import SaveRecordAsDraft201Response as SaveRecordAsDraft201Response
from dedi_client.models.save_record_as_draft_request import SaveRecordAsDraftRequest as SaveRecordAsDraftRequest
from dedi_client.models.search_records200_response import SearchRecords200Response as SearchRecords200Response
from dedi_client.models.search_records200_response_data_inner import SearchRecords200ResponseDataInner as SearchRecords200ResponseDataInner
from dedi_client.models.subscribe_to_watch201_response import SubscribeToWatch201Response as SubscribeToWatch201Response
from dedi_client.models.subscribe_to_watch201_response_data import SubscribeToWatch201ResponseData as SubscribeToWatch201ResponseData
from dedi_client.models.subscribe_to_watch_request import SubscribeToWatchRequest as SubscribeToWatchRequest
from dedi_client.models.success_response import SuccessResponse as SuccessResponse
from dedi_client.models.suspend_record200_response import SuspendRecord200Response as SuspendRecord200Response
from dedi_client.models.update_namespace_request import UpdateNamespaceRequest as UpdateNamespaceRequest
from dedi_client.models.update_record_request import UpdateRecordRequest as UpdateRecordRequest
from dedi_client.models.update_registry_request import UpdateRegistryRequest as UpdateRegistryRequest
from dedi_client.models.user import User as User
from dedi_client.models.verify_domain_request import VerifyDomainRequest as VerifyDomainRequest
from dedi_client.models.verify_email200_response import VerifyEmail200Response as VerifyEmail200Response
from dedi_client.models.verify_email200_response_data import VerifyEmail200ResponseData as VerifyEmail200ResponseData
from dedi_client.models.verify_namespace_lookup_request import VerifyNamespaceLookupRequest as VerifyNamespaceLookupRequest
from dedi_client.models.verify_record_lookup_request import VerifyRecordLookupRequest as VerifyRecordLookupRequest
from dedi_client.models.verify_registry_lookup_request import VerifyRegistryLookupRequest as VerifyRegistryLookupRequest
from dedi_client.models.watch_subscription import WatchSubscription as WatchSubscription

